// <auto-generated />
using System;
using LinguaReadApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinguaReadApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501073848_AddHardcoverIntegration")]
    partial class AddHardcoverIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinguaReadApi.Models.AudiobookTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("AudiobookTracks");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<int?>("HardcoverBookId")
                        .HasColumnType("integer");

                    b.Property<int?>("HardcoverEditionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HardcoverLastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HardcoverMatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HardcoverUserBookId")
                        .HasColumnType("integer");

                    b.Property<int?>("HardcoverUserBookReadId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<string>("Isbn13")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("KnownWords")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastReadPartId")
                        .HasColumnType("integer");

                    b.Property<int?>("LastReadTextId")
                        .HasColumnType("integer");

                    b.Property<int>("LearningWords")
                        .HasColumnType("integer");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalWords")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId");

                    b.HasIndex("FolderId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LastReadTextId");

                    b.HasIndex("UserId", "HardcoverBookId")
                        .IsUnique()
                        .HasFilter("\"HardcoverBookId\" IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LinguaReadApi.Models.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FolderId"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("FolderId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("UserId", "ParentFolderId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("CharacterSubstitutions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DeepLTargetCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GeminiTargetCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActiveForTranslation")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RightToLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowRomanization")
                        .HasColumnType("boolean");

                    b.Property<string>("SplitSentences")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WordCharacters")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WordsRead")
                        .HasColumnType("integer");

                    b.HasKey("LanguageId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("LinguaReadApi.Models.LanguageDictionary", b =>
                {
                    b.Property<int>("DictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DictionaryId"));

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UrlTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("DictionaryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageDictionaries");
                });

            modelBuilder.Entity("LinguaReadApi.Models.LanguageSentenceSplitException", b =>
                {
                    b.Property<int>("ExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExceptionId"));

                    b.Property<string>("ExceptionString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.HasKey("ExceptionId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageSentenceSplitExceptions");
                });

            modelBuilder.Entity("LinguaReadApi.Models.SrsCardReview", b =>
                {
                    b.Property<int>("SrsCardReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SrsCardReviewId"));

                    b.Property<DateTime?>("BuriedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentLearningStepIndex")
                        .HasColumnType("integer");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("double precision");

                    b.Property<int>("Flag")
                        .HasColumnType("integer");

                    b.Property<bool>("HasEverGraduated")
                        .HasColumnType("boolean");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLearning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("SrsCardReviewId");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "NextReviewAt");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique();

                    b.ToTable("SrsCardReviews");
                });

            modelBuilder.Entity("LinguaReadApi.Models.SrsPhrase", b =>
                {
                    b.Property<int>("SrsPhraseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SrsPhraseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TextId")
                        .HasColumnType("integer");

                    b.Property<string>("TextTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("SrsPhraseId");

                    b.HasIndex("TextId");

                    b.HasIndex("UserId");

                    b.HasIndex("WordId");

                    b.ToTable("SrsPhrases");
                });

            modelBuilder.Entity("LinguaReadApi.Models.SrsReviewLog", b =>
                {
                    b.Property<int>("SrsReviewLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SrsReviewLogId"));

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<int>("OldCurrentLearningStepIndex")
                        .HasColumnType("integer");

                    b.Property<double>("OldEaseFactor")
                        .HasColumnType("double precision");

                    b.Property<bool>("OldHasEverGraduated")
                        .HasColumnType("boolean");

                    b.Property<int>("OldInterval")
                        .HasColumnType("integer");

                    b.Property<bool>("OldIsLearning")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OldLastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OldNextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OldRepetitions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SrsCardReviewId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SrsReviewLogId");

                    b.HasIndex("SrsCardReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("SrsReviewLogs");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Text", b =>
                {
                    b.Property<int>("TextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TextId"));

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("text");

                    b.Property<int?>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAudioLesson")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PartNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SrtContent")
                        .HasColumnType("text");

                    b.Property<string>("StructuredContent")
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WordLinkingStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TextId");

                    b.HasIndex("BookId");

                    b.HasIndex("FolderId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("LinguaReadApi.Models.TextWord", b =>
                {
                    b.Property<int>("TextWordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TextWordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TextId")
                        .HasColumnType("integer");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("TextWordId");

                    b.HasIndex("WordId");

                    b.HasIndex("TextId", "WordId")
                        .IsUnique();

                    b.ToTable("TextWords");
                });

            modelBuilder.Entity("LinguaReadApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int?>("ListeningDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("IX_UserActivities_UserId_Timestamp");

                    b.HasIndex("UserId", "LanguageId", "Timestamp")
                        .HasDatabaseName("IX_UserActivities_UserId_LanguageId_Timestamp");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserAudioLessonProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("TextId")
                        .HasColumnType("integer");

                    b.Property<double?>("CurrentPosition")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "TextId");

                    b.HasIndex("TextId");

                    b.ToTable("UserAudioLessonProgresses");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserBookProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<double?>("CurrentAudiobookPosition")
                        .HasColumnType("double precision");

                    b.Property<int?>("CurrentAudiobookTrackId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.HasIndex("CurrentAudiobookTrackId");

                    b.ToTable("UserBookProgresses");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserGoal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GoalId"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BaselineValue")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedTzOffsetMin")
                        .HasColumnType("integer");

                    b.Property<long?>("CurrentPeriodBaseline")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("CurrentPeriodStart")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Recurrence")
                        .HasColumnType("integer");

                    b.Property<long>("TargetValue")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GoalId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "ArchivedAt");

                    b.HasIndex("UserId", "LanguageId");

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserGoalPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodId"));

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<long>("FinalProgress")
                        .HasColumnType("bigint");

                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<long>("TargetAtTime")
                        .HasColumnType("bigint");

                    b.HasKey("PeriodId");

                    b.HasIndex("GoalId", "PeriodEnd");

                    b.ToTable("UserGoalPeriods");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserLanguageStatistics", b =>
                {
                    b.Property<int>("UserLanguageStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserLanguageStatisticsId"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalBooksCompleted")
                        .HasColumnType("integer");

                    b.Property<long>("TotalSecondsListened")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTextCompletions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTextsCompleted")
                        .HasColumnType("integer");

                    b.Property<long>("TotalWordsRead")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserLanguageStatisticsId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguageStatistics");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserSentenceProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("TextId")
                        .HasColumnType("integer");

                    b.Property<string>("CreditedSegmentIndicesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreditedWordCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastSegmentIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "TextId");

                    b.HasIndex("TextId");

                    b.ToTable("UserSentenceProgresses");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoAdvanceToNextLesson")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoMoveFinishedLessons")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoTranslateOnOpen")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoTranslateWords")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentAudiobookPosition")
                        .HasColumnType("double precision");

                    b.Property<int?>("CurrentAudiobookTrackId")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultLanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("DiscordTimezoneOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("DiscordWebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("DiscordWeeklyReportDayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("DiscordWeeklyReportEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("DiscordWeeklyReportHourLocal")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DiscordWeeklyReportLastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HardcoverApiToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("HardcoverLastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HardcoverSyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighlightKnownWords")
                        .HasColumnType("boolean");

                    b.Property<int>("LeftPanelWidth")
                        .HasColumnType("integer");

                    b.Property<double>("LineSpacing")
                        .HasColumnType("double precision");

                    b.Property<string>("OpenRouterApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OpenRouterModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OpenRouterReasoningEffort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("OpenRouterReasoningEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OpenRouterStoryReasoningEffort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("OpenRouterStoryReasoningEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PauseOnWordClick")
                        .HasColumnType("boolean");

                    b.Property<int>("ReaderContentWidth")
                        .HasColumnType("integer");

                    b.Property<bool>("ReaderParagraphIndent")
                        .HasColumnType("boolean");

                    b.Property<string>("ReaderTextAlignment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReadingDensity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReadingUiMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SentenceAudioRepeats")
                        .HasColumnType("integer");

                    b.Property<bool>("SentenceMode")
                        .HasColumnType("boolean");

                    b.Property<bool>("SentenceTtsEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("SentenceTtsRate")
                        .HasColumnType("double precision");

                    b.Property<bool>("ShowDesktopLessonControls")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowProgressStats")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowWordInfoPanel")
                        .HasColumnType("boolean");

                    b.Property<int>("SrsCurrentStreak")
                        .HasColumnType("integer");

                    b.Property<int>("SrsDailyNewCardsStudied")
                        .HasColumnType("integer");

                    b.Property<int>("SrsDailyReviewsStudied")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SrsDailyStudyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SrsLapseMinimumIntervalDays")
                        .HasColumnType("integer");

                    b.Property<string>("SrsLearningStepMinutes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SrsLongestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("SrsMaxIntervalDays")
                        .HasColumnType("integer");

                    b.Property<int>("SrsMaxNewCards")
                        .HasColumnType("integer");

                    b.Property<int>("SrsMaxReviews")
                        .HasColumnType("integer");

                    b.Property<string>("SrsReviewOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextFont")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TextSize")
                        .HasColumnType("integer");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TooltipOnlyForSavedWords")
                        .HasColumnType("boolean");

                    b.Property<string>("TranslationTargetLanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseOpenRouter")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("WordId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId", "Term")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("LinguaReadApi.Models.WordTranslation", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WordId");

                    b.ToTable("WordTranslations");
                });

            modelBuilder.Entity("LinguaReadApi.Models.AudiobookTrack", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Book", "Book")
                        .WithMany("AudiobookTracks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Book", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Folder", "Folder")
                        .WithMany("Books")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.Text", "LastReadText")
                        .WithMany()
                        .HasForeignKey("LastReadTextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Language");

                    b.Navigation("LastReadText");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.BookTag", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Folder", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaReadApi.Models.Folder", "ParentFolder")
                        .WithMany("ChildFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("ParentFolder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.LanguageDictionary", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany("Dictionaries")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("LinguaReadApi.Models.LanguageSentenceSplitException", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany("SentenceSplitExceptions")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("LinguaReadApi.Models.SrsCardReview", b =>
                {
                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LinguaReadApi.Models.SrsPhrase", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Text");

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LinguaReadApi.Models.SrsReviewLog", b =>
                {
                    b.HasOne("LinguaReadApi.Models.SrsCardReview", "SrsCardReview")
                        .WithMany()
                        .HasForeignKey("SrsCardReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SrsCardReview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Text", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Book", "Book")
                        .WithMany("Texts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LinguaReadApi.Models.Folder", "Folder")
                        .WithMany("Texts")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany("Texts")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany("Texts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Folder");

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.TextWord", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Text", "Text")
                        .WithMany("TextWords")
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.Word", "Word")
                        .WithMany("TextWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Text");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserActivity", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserAudioLessonProgress", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Text");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserBookProgress", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.AudiobookTrack", "CurrentAudiobookTrack")
                        .WithMany()
                        .HasForeignKey("CurrentAudiobookTrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("CurrentAudiobookTrack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserGoal", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserGoalPeriod", b =>
                {
                    b.HasOne("LinguaReadApi.Models.UserGoal", "Goal")
                        .WithMany("Periods")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserLanguageStatistics", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserSentenceProgress", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Text");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserSettings", b =>
                {
                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("LinguaReadApi.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Word", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Language", "Language")
                        .WithMany("Words")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinguaReadApi.Models.User", "User")
                        .WithMany("Words")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaReadApi.Models.WordTranslation", b =>
                {
                    b.HasOne("LinguaReadApi.Models.Word", "Word")
                        .WithOne("Translation")
                        .HasForeignKey("LinguaReadApi.Models.WordTranslation", "WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Book", b =>
                {
                    b.Navigation("AudiobookTracks");

                    b.Navigation("BookTags");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Folder", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("ChildFolders");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Language", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Dictionaries");

                    b.Navigation("SentenceSplitExceptions");

                    b.Navigation("Texts");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Tag", b =>
                {
                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Text", b =>
                {
                    b.Navigation("TextWords");
                });

            modelBuilder.Entity("LinguaReadApi.Models.User", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Texts");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("LinguaReadApi.Models.UserGoal", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("LinguaReadApi.Models.Word", b =>
                {
                    b.Navigation("TextWords");

                    b.Navigation("Translation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
